#include <string>
std::string message = "Faust: Der Tragoedie Erster Teil\n"
"Nacht.\n"
"In einem hochgewoelbten, engen gotischen Zimmer Faust, unruhig auf seinem Sessel am Pulte.\n"
"Faust:\n"
"Habe nun, ach! Philosophie,\n"
"Juristerei und Medizin,\n"
"Und leider auch Theologie\n"
"Durchaus studiert, mit heissem Bemuehn.\n"
"Da steh ich nun, ich armer Tor!\n"
"Und bin so klug als wie zuvor;\n"
"Heisse Magister, heisse Doktor gar\n"
"Und ziehe schon an die zehen Jahr\n"
"Herauf, herab und quer und krumm\n"
"Meine Schueler an der Nase herum –\n"
"Und sehe, dass wir nichts wissen koennen!\n"
"Das will mir schier das Herz verbrennen.\n"
"Zwar bin ich gescheiter als all die Laffen,\n"
"Doktoren, Magister, Schreiber und Pfaffen;\n"
"Mich plagen keine Skrupel noch Zweifel,\n"
"Fuerchte mich weder vor Hoelle noch Teufel –\n"
"Dafuer ist mir auch alle Freud entrissen,\n"
"Bilde mir nicht ein, was Rechts zu wissen,\n"
"Bilde mir nicht ein, ich koennte was lehren,\n"
"Die Menschen zu bessern und zu bekehren.\n"
"Auch hab ich weder Gut noch Geld,\n"
"Noch Ehr und Herrlichkeit der Welt;\n"
"Es moechte kein Hund so laenger leben!\n"
"Drum hab ich mich der Magie ergeben,\n"
"Ob mir durch Geistes Kraft und Mund\n"
"Nicht manch Geheimnis wuerde kund;\n"
"Dass ich nicht mehr mit saurem Schweiss\n"
"Zu sagen brauche, was ich nicht weiss;\n"
"Dass ich erkenne, was die Welt\n"
"Im Innersten zusammenhaelt,\n"
"Schau alle Wirkenskraft und Samen,\n"
"Und tu nicht mehr in Worten kramen.\n"
"O saehst du, voller Mondenschein,\n"
"Zum letzenmal auf meine Pein,\n"
"Den ich so manche Mitternacht\n"
"An diesem Pult herangewacht:\n"
"Dann ueber Buechern und Papier,\n"
"Truebsel'ger Freund, erschienst du mir!\n"
"Ach! koennt ich doch auf Bergeshoehn\n"
"In deinem lieben Lichte gehn,\n"
"Um Bergeshoehle mit Geistern schweben,\n"
"Auf Wiesen in deinem Daemmer weben,\n"
"Von allem Wissensqualm entladen,\n"
"In deinem Tau gesund mich baden!\n"
"Weh! steck ich in dem Kerker noch?\n"
"Verfluchtes dumpfes Mauerloch,\n"
"Wo selbst das liebe Himmelslicht\n"
"Trueb durch gemalte Scheiben bricht!\n"
"Beschraenkt mit diesem Buecherhauf,\n"
"den Wuerme nagen, Staub bedeckt,\n"
"Den bis ans hohe Gewoelb hinauf\n"
"Ein angeraucht Papier umsteckt;\n"
"Mit Glaesern, Buechsen rings umstellt,\n"
"Mit Instrumenten vollgepfropft,\n"
"Urvaeter Hausrat drein gestopft –\n"
"Das ist deine Welt! das heisst eine Welt!\n"
"Und fragst du noch, warum dein Herz\n"
"Sich bang in deinem Busen klemmt?\n"
"Warum ein unerklaerter Schmerz\n"
"Dir alle Lebensregung hemmt?\n"
"Statt der lebendigen Natur,\n"
"Da Gott die Menschen schuf hinein,\n"
"Umgibt in Rauch und Moder nur\n"
"Dich Tiergeripp und Totenbein.\n"
"Flieh! auf! hinaus ins weite Land!\n"
"Und dies geheimnisvolle Buch,\n"
"Von Nostradamus' eigner Hand,\n"
"Ist dir es nicht Geleit genug?\n"
"Erkennest dann der Sterne Lauf,\n"
"Und wenn Natur dich Unterweist,\n"
"Dann geht die Seelenkraft dir auf,\n"
"Wie spricht ein Geist zum andren Geist.\n"
"Umsonst, dass trocknes Sinnen hier\n"
"Die heil'gen Zeichen dir erklaert:\n"
"Ihr schwebt, ihr Geister, neben mir;\n"
"Antwortet mir, wenn ihr mich hoert!\n"
"(Er schlaegt das Buch auf und erblickt das Zeichen des Makrokosmus.)\n"
"Ha! welche Wonne fliesst in diesem Blick\n"
"Auf einmal mir durch alle meine Sinnen!\n"
"Ich fuehle junges, heil'ges Lebensglueck\n"
"Neugluehend mir durch Nerv' und Adern rinnen.\n"
"War es ein Gott, der diese Zeichen schrieb,\n"
"Die mir das innre Toben stillen,\n"
"Das arme Herz mit Freude fuellen,\n"
"Und mit geheimnisvollem Trieb\n"
"Die Kraefte der Natur rings um mich her enthuellen?\n"
"Bin ich ein Gott? Mir wird so licht!\n"
"Ich schau in diesen reinen Zuegen\n"
"Die wirkende Natur vor meiner Seele liegen.\n"
"Jetzt erst erkenn ich, was der Weise spricht:\n"
"Die Geisterwelt ist nicht verschlossen;\n"
"Dein Sinn ist zu, dein Herz ist tot!\n"
"Auf, bade, Schueler, unverdrossen\n"
"Die ird'sche Brust im Morgenrot!\n"
"(er beschaut das Zeichen.)\n"
"Wie alles sich zum Ganzen webt,\n"
"Eins in dem andern wirkt und lebt!\n"
"Wie Himmelskraefte auf und nieder steigen\n"
"Und sich die goldnen Eimer reichen!\n"
"Mit segenduftenden Schwingen\n"
"Vom Himmel durch die Erde dringen,\n"
"Harmonisch all das All durchklingen!\n"
"Welch Schauspiel! Aber ach! ein Schauspiel nur!\n"
"Wo fass ich dich, unendliche Natur?\n"
"Euch Brueste, wo? Ihr Quellen alles Lebens,\n"
"An denen Himmel und Erde haengt,\n"
"Dahin die welke Brust sich draengt –\n"
"Ihr quellt, ihr traenkt, und schmacht ich so vergebens?\n"
"(er schlaegt unwillig das Buch um und erblickt das Zeichen des Erdgeistes.)\n"
"Wie anders wirkt dies Zeichen auf mich ein!\n"
"Du, Geist der Erde, bist mir naeher;\n"
"Schon fuehl ich meine Kraefte hoeher,\n"
"Schon glueh ich wie von neuem Wein.\n"
"Ich fuehle Mut, mich in die Welt zu wagen,\n"
"Der Erde Weh, der Erde Glueck zu tragen,\n"
"Mit Stuermen mich herumzuschlagen\n"
"Und in des Schiffbruchs Knirschen nicht zu zagen.\n"
"Es woelkt sich ueber mir –\n"
"Der Mond verbirgt sein Licht –\n"
"Die Lampe schwindet!\n"
"Es dampft! Es zucken rote Strahlen\n"
"Mir um das Haupt – Es weht\n"
"Ein Schauer vom Gewoelb herab\n"
"Und fasst mich an!\n"
"Ich fuehl's, du schwebst um mich, erflehter Geist\n"
"Enthuelle dich!\n"
"Ha! wie's in meinem Herzen reisst!\n"
"Zu neuen Gefuehlen\n"
"All meine Sinnen sich erwuehlen!\n"
"Ich fuehle ganz mein Herz dir hingegeben!\n"
"Du musst! du musst! und kostet es mein Leben!\n"
"(Er fasst das Buch und spricht das Zeichen des Geistes geheimnisvoll aus. Es zuckt eine roetliche Flamme, der Geist erscheint in der Flamme.)\n"
"Geist:\n"
"Wer ruft mir?\n"
"Faust (abgewendet):\n"
"			Schreckliches Gesicht!\n"
"Geist:\n"
"Du hast mich maechtig angezogen,\n"
"An meiner Sphaere lang gesogen,\n"
"Und nun –\n"
"Faust:\n"
"			Weh! ich ertrag dich nicht!\n"
"Geist:\n"
"Du flehst, eratmend mich zu schauen,\n"
"Meine Stimme zu hoeren, mein Antlitz zu sehn;\n"
"Mich neigt dein maechtig Seelenflehn,\n"
"Da bin ich! – Welch erbaermlich Grauen\n"
"Fasst uebermenschen dich! Wo ist der Seele Ruf?\n"
"Wo ist die Brust, die eine Welt in sich erschuf\n"
"Und trug und hegte, die mit Freudebeben\n"
"Erschwoll, sich uns, den Geistern, gleich zu heben?\n"
"Wo bist du, Faust, des Stimme mir erklang,\n"
"Der sich an mich mit allen Kraeften drang?\n"
"Bist du es, der, von meinem Hauch umwittert,\n"
"In allen Lebenslagen zittert,\n"
"Ein furchtsam weggekruemmter Wurm?\n"
"Faust:\n"
"Soll ich dir, Flammenbildung, weichen?\n"
"Ich bin's, bin Faust, bin deinesgleichen!\n"
"Geist:\n"
"In Lebensfluten, im Tatensturm\n"
"Wall ich auf und ab,\n"
"Wehe hin und her!\n"
"Geburt und Grab,\n"
"Ein ewiges Meer,\n"
"Ein wechselndes Wehen,\n"
"Ein gluehend Leben,\n"
"So schaff ich am laufenden Webstuhl der Zeit\n"
"Und wirke der Gottheit lebendiges Kleid.\n"
"Faust:\n"
"Der du die weite Welt umschweifst,\n"
"Geschaeftiger Geist, wie nah fuehl ich mich dir!\n"
"Geist:\n"
"Du gleichst dem Geist, den du begreifst,\n"
"Nicht mir!\n"
"(verschwindet)\n"
"Faust (zusammenstuerzend) :\n"
"Nicht dir?\n"
"Wem denn?\n"
"Ich Ebenbild der Gottheit!\n"
"Und nicht einmal dir!\n"
"(es klopft)\n"
"O Tod! ich kenn's – das ist mein Famulus –\n"
"Es wird mein schoenstes Glueck zunichte!\n"
"Dass diese Fuelle der Geschichte\n"
"Der trockne Schleicher stoeren muss!\n"
"Wagner im Schlafrock und der Nachtmuetze, eine Lampe in der Hand. Faust wendet sich unwillig.\n"
"Wagner:\n"
"Verzeiht! ich hoer euch deklamieren;\n"
"Ihr last gewiss ein griechisch Trauerspiel?\n"
"In dieser Kunst moecht ich was profitieren,\n"
"Denn heutzutage wirkt das viel.\n"
"Ich hab es oefters ruehmen hoeren,\n"
"Ein Komoediant koennt einen Pfarrer lehren.\n"
"Faust:\n"
"Ja, wenn der Pfarrer ein Komoediant ist;\n"
"Wie das denn wohl zuzeiten kommen mag.\n"
"Wagner:\n"
"Ach! wenn man so in sein Museum gebannt ist,\n"
"Und sieht die Welt kaum einen Feiertag,\n"
"Kaum durch ein Fernglas, nur von weitem,\n"
"Wie soll man sie durch ueberredung leiten?\n"
"Faust:\n"
"Wenn ihr's nicht fuehlt, ihr werdet's nicht erjagen,\n"
"Wenn es nicht aus der Seele dringt\n"
"Und mit urkraeftigem Behagen\n"
"Die Herzen aller Hoerer zwingt.\n"
"Sitzt ihr nur immer! leimt zusammen,\n"
"Braut ein Ragout von andrer Schmaus\n"
"Und blast die kuemmerlichen Flammen\n"
"Aus eurem Aschenhaeuschen 'raus!\n"
"Bewundrung von Kindern und Affen,\n"
"Wenn euch darnach der Gaumen steht –\n"
"Doch werdet ihr nie Herz zu Herzen schaffen,\n"
"Wenn es euch nicht von Herzen geht.\n"
"Wagner:\n"
"Allein der Vortrag macht des Redners Glueck;\n"
"Ich fuehl es wohl, noch bin ich weit zurueck.\n"
"Faust:\n"
"Such Er den redlichen Gewinn!\n"
"Sei Er kein schellenlauter Tor!\n"
"Es traegt Verstand und rechter Sinn\n"
"Mit wenig Kunst sich selber vor!\n"
"Und wenn's euch Ernst ist, was zu sagen,\n"
"Ist's noetig, Worten nachzujagen?\n"
"Ja, eure Reden, die so blinkend sind,\n"
"In denen ihr der Menschheit Schnitzel kraeuselt,\n"
"Sind unerquicklich wie der Nebelwind,\n"
"Der herbstlich durch die duerren Blaetter saeuselt!\n"
"Wagner:\n"
"Ach Gott! die Kunst ist lang;\n"
"Und kurz ist unser Leben.\n"
"Mir wird, bei meinem kritischen Bestreben,\n"
"Doch oft um Kopf und Busen bang.\n"
"Wie schwer sind nicht die Mittel zu erwerben,\n"
"Durch die man zu den Quellen steigt!\n"
"Und eh man nur den halben Weg erreicht,\n"
"Muss wohl ein armer Teufel sterben.\n"
"Faust:\n"
"Das Pergament, ist das der heil'ge Bronnen,\n"
"Woraus ein Trunk den Durst auf ewig stillt?\n"
"Erquickung hast du nicht gewonnen,\n"
"Wenn sie dir nicht aus eigner Seele quillt.\n"
"Wagner:\n"
"Verzeiht! es ist ein gross Ergetzen,\n"
"Sich in den Geist der Zeiten zu versetzen;\n"
"Zu schauen, wie vor uns ein weiser Mann gedacht,\n"
"Und wie wir's dann zuletzt so herrlich weit gebracht.\n"
"Faust:\n"
"O ja, bis an die Sterne weit!\n"
"Mein Freund, die Zeiten der Vergangenheit\n"
"Sind uns ein Buch mit sieben Siegeln.\n"
"Was ihr den Geist der Zeiten heisst,\n"
"Das ist im Grund der Herren eigner Geist,\n"
"In dem die Zeiten sich bespiegeln.\n"
"Da ist's denn wahrlich oft ein Jammer!\n"
"Man laeuft euch bei dem ersten Blick davon.\n"
"Ein Kehrichtfass und eine Rumpelkammer\n"
"Und hoechstens eine Haupt- und Staatsaktion\n"
"Mit trefflichen pragmatischen Maximen,\n"
"Wie sie den Puppen wohl im Munde ziemen!\n"
"Wagner:\n"
"Allein die Welt! des Menschen Herz und Geist!\n"
"Moecht jeglicher doch was davon erkennen.\n"
"Faust:\n"
"Ja, was man so erkennen heisst!\n"
"Wer darf das Kind beim Namen nennen?\n"
"Die wenigen, die was davon erkannt,\n"
"Die toericht g'nug ihr volles Herz nicht wahrten,\n"
"Dem Poebel ihr Gefuehl, ihr Schauen offenbarten,\n"
"Hat man von je gekreuzigt und verbrannt.\n"
"Ich bitt Euch, Freund, es ist tief in der Nacht,\n"
"Wir muessen's diesmal unterbrechen.\n"
"Wagner:\n"
"Ich haette gern nur immer fortgewacht,\n"
"Um so gelehrt mit Euch mich zu besprechen.\n"
"Doch morgen, als am ersten Ostertage,\n"
"Erlaubt mir ein' und andre Frage.\n"
"Mit Eifer hab' ich mich der Studien beflissen;\n"
"Zwar weiss ich viel, doch moecht' ich alles wissen.\n"
"(Ab.)\n"
"Faust (allein):\n"
"Wie nur dem Kopf nicht alle Hoffnung schwindet,\n"
"Der immerfort an schalem Zeuge klebt,\n"
"Mit gier'ger Hand nach Schaetzen graebt,\n"
"Und froh ist, wenn er Regenwuermer findet!\n"
"Darf eine solche Menschenstimme hier,\n"
"Wo Geisterfuelle mich umgab, ertoenen?\n"
"Doch ach! fuer diesmal dank ich dir,\n"
"Dem aermlichsten von allen Erdensoehnen.\n"
"Du rittest mich von der Verzweiflung los,\n"
"Die mir die Sinne schon zerstoeren wollte.\n"
"Ach! die Erscheinung war so riesengross,\n"
"Dass ich mich recht als Zwerg empfinden sollte.\n"
"Ich, Ebenbild der Gottheit, das sich schon\n"
"Ganz nah geduenkt dem Spiegel ew'ger Wahrheit,\n"
"Sein selbst genoss in Himmelsglanz und Klarheit,\n"
"Und abgestreift den Erdensohn;\n"
"Ich, mehr als Cherub, dessen freie Kraft\n"
"Schon durch die Adern der Natur zu fliessen\n"
"Und, schaffend, Goetterleben zu geniessen\n"
"Sich ahnungsvoll vermass, wie muss ich's buessen!\n"
"Ein Donnerwort hat mich hinweggerafft.\n"
"Nicht darf ich dir zu gleichen mich vermessen;\n"
"Hab ich die Kraft dich anzuziehn besessen,\n"
"So hatt ich dich zu halten keine Kraft.\n"
"Zu jenem sel'gen Augenblicke\n"
"Ich fuehlte mich so klein, so gross;\n"
"Du stiessest grausam mich zurueck,\n"
"Ins ungewisse Menschenlos.\n"
"Wer lehret mich? was soll ich meiden?\n"
"Soll ich gehorchen jenem Drang?\n"
"Ach! unsre Taten selbst, so gut als unsre Leiden,\n"
"Sie hemmen unsres Lebens Gang.\n"
"Dem Herrlichsten, was auch der Geist empfangen,\n"
"Draengt immer fremd und fremder Stoff sich an;\n"
"Wenn wir zum Guten dieser Welt gelangen,\n"
"Dann heisst das Bessre Trug und Wahn.\n"
"Die uns das Leben gaben, herrliche Gefuehle\n"
"Erstarren in dem irdischen Gewuehle.\n"
"Wenn Phantasie sich sonst mit kuehnem Flug\n"
"Und hoffnungsvoll zum Ewigen erweitert,\n"
"So ist ein kleiner Raum ihr genug,\n"
"Wenn Glueck auf Glueck im Zeitenstrudel scheitert.\n"
"Die Sorge nistet gleich im tiefen Herzen,\n"
"Dort wirket sie geheime Schmerzen,\n"
"Unruhig wiegt sie sich und stoeret Luft und Ruh;\n"
"Sie deckt sich stets mit neuen Masken zu,\n"
"Sie mag als Haus und Hof, als Weib und Kind erscheinen,\n"
"Als Feuer, Wasser, Dolch und Gift;\n"
"Du bebst vor allem, was nicht trifft,\n"
"Und was du nie verlierst, das musst du stets beweinen.\n"
"Den Goettern gleich ich nicht! zu tief ist es gefuehlt;\n"
"Dem Wurme gleich ich, der den Staub durchwuehlt,\n"
"Den, wie er sich im Staube naehrend lebt,\n"
"Des Wandrers Tritt vernichtet und begraebt.\n"
"Ist es nicht Staub, was diese hohe Wand\n"
"Aus hundert Faechern mit verenget?\n"
"Der Troedel, der mit tausendfachem Tand\n"
"In dieser Mottenwelt mich draenget?\n"
"Hier soll ich finden, was mir fehlt?\n"
"Soll ich vielleicht in tausend Buechern lesen,\n"
"Dass ueberall die Menschen sich gequaelt,\n"
"Dass hie und da ein Gluecklicher gewesen? –\n"
"Was grinsest du mir, hohler Schaedel, her?\n"
"Als dass dein Hirn, wie meines, einst verwirret\n"
"Den leichten Tag gesucht und in der Daemmrung schwer,\n"
"Mit Luft nach Wahrheit, jaemmerlich geirret.\n"
"Ihr Instrumente freilich spottet mein,\n"
"Mit Rad und Kaemmen, Walz und Buegel:\n"
"Ich stand am Tor, ihr solltet Schluessel sein;\n"
"Zwar euer Bart ist kraus, doch hebt ihr nicht die Riegel.\n"
"Geheimnisvoll am lichten Tag\n"
"Laesst sich Natur des Schleiers nicht berauben,\n"
"Und was sie deinem Geist nicht offenbaren mag,\n"
"Das zwingst du ihr nicht ab mit Hebeln und mit Schrauben.\n"
"Du alt Geraete, das ich nicht gebraucht,\n"
"Du stehst nur hier, weil dich mein Vater brauchte.\n"
"Du alte Rolle, du wirst angeraucht,\n"
"Solang an diesem Pult die truebe Lampe schmauchte.\n"
"Weit besser haett ich doch mein Weniges verprasst,\n"
"Als mit dem Wenigen belastet hier zu schwitzen!\n"
"Was du ererbt von deinem Vater hast,\n"
"Erwirb es, um es zu besitzen.\n"
"Was man nicht nuetzt, ist eine schwere Last,\n"
"Nur was der Augenblick erschafft, das kann er nuetzen.\n"
"Doch warum heftet sich mein Blick auf jene Stelle?\n"
"Ist jenes Flaeschchen dort den Augen ein Magnet?\n"
"Warum wird mir auf einmal lieblich helle,\n"
"Als wenn im naecht'gen Wald uns Mondenglanz umweht?\n"
"Ich gruesse dich, du einzige Phiole,\n"
"Die ich mit Andacht nun herunterhole!\n"
"In dir verehr ich Menschenwitz und Kunst.\n"
"Du Inbegriff der holden Schlummersaefte,\n"
"Du Auszug aller toedlich feinen Kraefte,\n"
"Erweise deinem Meister deine Gunst!\n"
"Ich sehe dich, es wird der Schmerz gelindert,\n"
"Ich fasse dich, das Streben wird gemindert,\n"
"Des Geistes Flutstrom ebbet nach und nach.\n"
"Ins hohe Meer werd ich hinausgewiesen,\n"
"Die Spiegelflut erglaenzt zu meinen Fuessen,\n"
"Zu neuen Ufern lockt ein neuer Tag.\n"
"Ein Feuerwagen schwebt, auf leichten Schwingen,\n"
"An mich heran! Ich fuehle mich bereit,\n"
"Auf neuer Bahn den aether zu durchdringen,\n"
"Zu neuen Sphaeren reiner Taetigkeit.\n"
"Dies hohe Leben, diese Goetterwonne!\n"
"Du, erst noch Wurm, und die verdienest du?\n"
"Ja, kehre nur der holden Erdensonne\n"
"Entschlossen deinen Ruecken zu!\n"
"Vermesse dich, die Pforten aufzureissen,\n"
"Vor denen jeder gern vorueberschleicht!\n"
"Hier ist es Zeit, durch Taten zu beweisen,\n"
"Das Manneswuerde nicht der Goetterhoehe weicht,\n"
"Vor jener dunkeln Hoehle nicht zu beben,\n"
"In der sich Phantasie zu eigner Qual verdammt,\n"
"Nach jenem Durchgang hinzustreben,\n"
"Um dessen engen Mund die ganze Hoelle flammt;\n"
"In diesem Schritt sich heiter zu entschliessen,\n"
"Und waer es mit Gefahr, ins Nichts dahin zu fliessen.\n"
"Nun komm herab, kristallne reine Schale!\n"
"Hervor aus deinem alten Futterale,\n"
"An die ich viele Jahre nicht gedacht!\n"
"Du glaenzetst bei der Vaeter Freudenfeste,\n"
"Erheitertest die ernsten Gaeste,\n"
"Wenn einer dich dem andern zugebracht.\n"
"Der vielen Bilder kuenstlich reiche Pracht,\n"
"Des Trinkers Pflicht, sie reimweis zu erklaeren,\n"
"Auf einen Zug die Hoehlung auszuleeren,\n"
"Erinnert mich an manche Jugendnacht.\n"
"Ich werde jetzt dich keinem Nachbar reichen,\n"
"Ich werde meinen Witz an deiner Kunst nicht zeigen.\n"
"Hier ist ein Saft, der eilig trunken macht;\n"
"Mit brauner Flut erfuellt er deine Hoehle.\n"
"Den ich bereit, den ich waehle,\n"
"Der letzte Trunk sei nun, mit ganzer Seele,\n"
"Als festlich hoher Gruss, dem Morgen zugebracht!\n"
"(Er setzt die Schale an den Mund.)\n"
"Glockenklang und Chorgesang.\n"
"Chor der Engel:\n"
"			Christ ist erstanden!\n"
"			Freude dem Sterblichen,\n"
"			Den die verderblichen,\n"
"			Schleichenden, erblichen\n"
"			Maengel unwanden.\n"
"Faust:\n"
"Welch tiefes Summen, welch heller Ton\n"
"Zieht mit Gewalt das Glas von meinem Munde?\n"
"Verkuendigt ihr dumpfen Glocken schon\n"
"Des Osterfestes erste Feierstunde?\n"
"Ihr Choere, singt ihr schon den troestlichen Gesang,\n"
"Der einst, um Grabes Nacht, von Engelslippen klang,\n"
"Gewissheit einem neuen Bunde?\n"
"Chor der Weiber:\n"
"			Mit Spezereien\n"
"			Hatten wir ihn gepflegt,\n"
"			Wir seine Treuen\n"
"			Hatten ihn hingelegt;\n"
"			Tuecher und Binden\n"
"			Reinlich unwanden wir,\n"
"			Ach! und wir finden\n"
"			Christ nicht mehr hier.\n"
"Chor der Engel:\n"
"			Christ ist erstanden!\n"
"			Selig der Liebende,\n"
"			Der die betruebende,\n"
"			Heilsam und uebende\n"
"			Pruefung bestanden.\n"
"Faust:\n"
"Was sucht ihr, maechtig und gelind,\n"
"Ihr Himmelstoene, mich am Staube?\n"
"Klingt dort umher, wo weiche Menschen sind.\n"
"Die Botschaft hoer ich wohl, allein mir fehlt der Glaube;\n"
"Das Wunder ist des Glaubens liebstes Kind.\n"
"Zu jenen Sphaeren wag ich nicht zu streben,\n"
"Woher die holde Nachricht toent;\n"
"Und doch, an diesen Klang von Jugend auf gewoehnt,\n"
"Ruft er auch jetzt zurueck mich in das Leben.\n"
"Sonst stuerzte sich der Himmelsliebe Kuss\n"
"Auf mich herab in ernster Sabbatstille;\n"
"Da klang so ahnungsvoll des Glockentones Fuelle,\n"
"Und ein Gebet war bruenstiger Genuss;\n"
"Ein unbegreiflich holdes Sehnen\n"
"Trieb mich, durch Wald und Wiesen hinzugehn,\n"
"Und unter tausend heissen Traenen\n"
"Fuehlt ich mir eine Welt entstehn.\n"
"Dies Lieb verkuendete der Jugend muntre Spiele,\n"
"Der Fruehlingsfeier freies Glueck;\n"
"Erinnrung haelt mich nun, mit kindlichem Gefuehle,\n"
"Vom letzten, ernsten Schritt zurueck.\n"
"O toenet fort, ihr suessen Himmelslieder!\n"
"Die Traene quillt, die Erde hat mich wieder!\n"
"Chor der Juenger:\n"
"			Hat der Begrabene\n"
"			Schon sich nach oben,\n"
"			Lebend Erhabene,\n"
"			Herrlich erhoben;\n"
"			Ist er in Werdeluft\n"
"			Schaffender Freude nah:\n"
"			Ach! an der Erde Brust\n"
"			Sind wir zum Leide da.\n"
"			Liess er die Seinen\n"
"			Schmachtend uns hier zurueck;\n"
"			Ach! wir beweinen,\n"
"			Meister, dein Glueck!\n"
"Chor der Engel:\n"
"			Christ ist erstanden,\n"
"			Aus der Verwesung Schoss.\n"
"			Reisset von Banden\n"
"			Freudig euch los!\n"
"			Taetig ihn preisenden,\n"
"			Liebe beweisenden,\n"
"			Bruederlich speisenden,\n"
"			Predigend reisenden,\n"
"			Wonne verheissenden\n"
"			Euch ist der Meister nah,\n"
"			Euch ist er da!\n"
"			Vor dem Tor\n"
"Spaziergaenger aller Art ziehen hinaus.\n"
"Einige Handwerksbursche:\n"
"Warum denn dort hinaus?\n"
"Andre:\n"
"Wir gehn hinaus aufs Jaegerhaus.\n"
"Die Ersten:\n"
"Wir aber wollen nach der Muehle wandern.\n"
"Ein Handwerksbursch:\n"
"Ich rat euch, nach dem Wasserhof zu gehn.\n"
"Zweiter:\n"
"Der Weg dahin ist gar nicht schoen.\n"
"Die Zweiten:\n"
"Was tust denn du?\n"
"Ein Dritter:\n"
"			Ich gehe mit den andern.\n"
"Vierter:\n"
"Nach Burgdorf kommt herauf, gewiss dort findet ihr\n"
"Die schoensten Maedchen und das beste Bier,\n"
"Und Haendel von der ersten Sorte.\n"
"Fuenfter:\n"
"Du ueberlustiger Gesell,\n"
"Juckt dich zum drittenmal das Fell?\n"
"Ich mag nicht hin, mir graut es vor dem Orte.\n"
"Dienstmaedchen:\n"
"Nein, nein! ich gehe nach der Stadt zurueck.\n"
"Andre:\n"
"Wir finden ihn gewiss bei jenen Pappeln stehen.\n"
"Erste:\n"
"Das ist fuer mich kein grosses Glueck;\n"
"Er wird an deiner Seite gehen,\n"
"Mit dir nur tanzt er auf dem Plan.\n"
"Was gehn mich deine Freuden an!\n"
"Andre:\n"
"Heut ist er sicher nicht allein,\n"
"Der Krauskopf, sagt er, wuerde bei ihm sein.\n"
"Schueler:\n"
"Blitz, wie die wackern Dirnen schreiten!\n"
"Herr Bruder, komm! wir muessen sie begleiten.\n"
"Ein starkes Bier, ein beizender Toback,\n"
"Und eine Magd im Putz, das ist nun mein Geschmack.\n"
"Buergermaedchen:\n"
"Da sieh mir nur die schoenen Knaben!\n"
"Es ist wahrhaftig eine Schmach:\n"
"Gesellschaft koennten sie die allerbeste haben,\n"
"Und laufen diesen Maegden nach!\n"
"Zweiter Schueler (zum ersten):\n"
"Nicht so geschwind! dort hinten kommen zwei,\n"
"Sie sind gar niedlich angezogen,\n"
"'s ist meine Nachbarin dabei;\n"
"Ich bin dem Maedchen sehr gewogen.\n"
"Sie gehen ihren stillen Schritt\n"
"Und nehmen uns doch auch am Ende mit.\n"
"Erster:\n"
"Herr Bruder, nein! Ich bin nicht gern geniert.\n"
"Geschwind! dass wir das Wildbret nicht verlieren.\n"
"Die Hand, die samstags ihren Besen fuehrt\n"
"Wird sonntags dich am besten karessieren.\n"
"Buerger:\n"
"Nein, er gefaellt mir nicht, der neue Burgemeister!\n"
"Nun, da er's ist, wird er nur taeglich dreister.\n"
"Und fuer die Stadt was tut denn er?\n"
"Wird es nicht alle Tage schlimmer?\n"
"Gehorchen soll man mehr als immer,\n"
"Und zahlen mehr als je vorher.\n"
"Bettler (singt):\n"
"			Ihr guten Herrn, ihr schoenen Frauen,\n"
"			So wohlgeputzt und backenrot,\n"
"			Belieb es euch, mich anzuschauen,\n"
"			Und seht und mildert meine Not!\n"
"			Lasst hier mich nicht vergebens leiern!\n"
"			Nur der ist froh, der geben mag.\n"
"			Ein Tag, den alle Menschen feiern,\n"
"			Er sei fuer mich ein Erntetag.\n"
"Andrer Buerger:\n"
"Nichts Bessers weiss ich mir an Sonn- und Feiertagen\n"
"Als ein Gespraech von Krieg und Kriegsgeschrei,\n"
"Wenn hinten, weit, in der Tuerkei,\n"
"Die Voelker aufeinander schlagen.\n"
"Man steht am Fenster, trinkt sein Glaeschen aus\n"
"Und sieht den Fluss hinab die bunten Schiffe gleiten;\n"
"Dann kehrt man abends froh nach Haus,\n"
"Und segnet Fried und Friedenszeiten.\n"
"Dritter Buerger:\n"
"Herr Nachbar, ja! so lass ich's auch geschehn:\n"
"Sie moegen sich die Koepfe spalten,\n"
"Mag alles durcheinander gehn;\n"
"Doch nur zu Hause bleib's beim alten.\n"
"Alte (zu den Buergermaedchen):\n"
"Ei! wie geputzt! das schoene junge Blut!\n"
"Wer soll sich nicht in euch vergaffen? –\n"
"Nur nicht so stolz! es ist schon gut!\n"
"Und was ihr wuenscht, das wuesst ich wohl zu schaffen.\n"
"Buergermaedchen:\n"
"Agathe, fort! ich nehme mich in acht,\n"
"Mit solchen Hexen oeffentlich zu gehen;\n"
"Sie liess mich zwar in Sankt Andreas' Nacht\n"
"Den kuenft'gen Liebsten leiblich sehen –\n"
"Die Andre:\n"
"Mir zeigte sie ihn im Kristall,\n"
"Soldatenhaft, mit mehreren Verwegnen;\n"
"Ich seh mich um, ich such ihn ueberall,\n"
"Allein mir will er nicht begegnen.\n"
"Soldaten:\n"
"			Burgen mit hohen\n"
"			Mauern und Zinnen,\n"
"			Maedchen mit stolzen\n"
"			Hoehnenden Sinnen\n"
"			Moecht ich gewinnen!\n"
"			Kuehn ist das Muehen,\n"
"			Herrlich der Lohn!\n"
"			Und die Trompete\n"
"			Lassen wir werben,\n"
"			Wie zu der Freude,\n"
"			So zum Verderben.\n"
"			Das ist ein Stuermen!\n"
"			Das ist ein Leben!\n"
"			Maedchen und Burgen\n"
"			Muessen sich geben.\n"
"			Kuehn ist das Muehen,\n"
"			Herrlich der Lohn!\n"
"			Und die Soldaten\n"
"			Ziehen davon.\n"
"Faust und Wagner.\n"
"Faust:\n"
"Vom Eise befreit sind Strom und Baeche\n"
"Durch des Fruehlings holden, belebenden Blick;\n"
"Im Tale gruenet Hoffnungsglueck;\n"
"Der alte Winter, in seiner Schwaeche,\n"
"Zog sich in rauhe Berge zurueck.\n"
"Von dorther sendet er, fliehend, nur\n"
"Ohnmaechtige Schauer kornigen Eises\n"
"In Streifen ueber die gruenende Flur;\n"
"Aber die Sonne duldet kein Weisses,\n"
"ueberall regt sich Bildung und Streben,\n"
"Alles will sie mit Farben beleben;\n"
"Doch an Blumen fehlt's im Revier\n"
"Sie nimmt geputzte Menschen dafuer.\n"
"Kehre dich um, von diesen Hoehen\n"
"Nach der Stadt zurueckzusehen.\n"
"Aus dem hohlen finstern Tor\n"
"Dringt ein buntes Gewimmel hervor.\n"
"Jeder sonnt sich heute so gern.\n"
"Sie feiern die Auferstehung des Herrn,\n"
"Denn sie sind selber auferstanden,\n"
"Aus niedriger Haeuser dumpfen Gemaechern,\n"
"Aus Handwerks- und Gewerbesbanden,\n"
"Aus dem Druck von Giebeln und Daechern,\n"
"Aus der Strassen quetschender Enge,\n"
"Aus der Kirchen ehrwuerdiger Nacht\n"
"Sind sie alle ans Licht gebracht.\n"
"Sieh nur, sieh! wie behend sich die Menge\n"
"Durch die Gaerten und Felder zerschlaegt,\n"
"Wie der Fluss, in Breit und Laenge\n"
"So manchen lustigen Nachen bewegt,\n"
"Und bis zum Sinken ueberladen\n"
"Entfernt sich dieser letzte Kahn.\n"
"Selbst von des Berges fernen Pfaden\n"
"Blinken uns farbige Kleider an.\n"
"Ich hoere schon des Dorfs Getuemmel,\n"
"Hier ist des Volkes wahrer Himmel,\n"
"Zufrieden jauchzet gross und klein:\n"
"Hier bin ich Mensch, hier darf ich's sein!\n"
"Wagner:\n"
"Mit Euch, Herr Doktor, zu spazieren\n"
"Ist ehrenvoll und ist Gewinn;\n"
"Doch wuerd ich nicht allein mich her verlieren,\n"
"Weil ich ein Feind von allem Rohen bin.\n"
"Das Fiedeln, Schreien, Kegelschieben\n"
"Ist mir ein gar verhasster Klang;\n"
"Sie toben wie vom boesen Geist getrieben\n"
"Und nennen's Freude. nennen's Gesang.\n"
"Bauern unter der Linde.\n"
"Tanz und Gesang.\n"
"			Der Schaefer putzte sich zum Tanz,\n"
"			Mit bunter Jacke, Band und Kranz,\n"
"			Schmuck war er angezogen.\n"
"			Schon um die Linde war es voll,\n"
"			Und alles tanzte schon wie toll.\n"
"			Juchhe! Juchhe!\n"
"			Juchheisa! Heisa! He!\n"
"			So ging der Fiedelbogen.\n"
"			Er drueckte hastig sich heran,\n"
"			Da stiess er an ein Maedchen an\n"
"			Mit seinem Ellenbogen;\n"
"			Die frische Dirne kehrt, sich um\n"
"			Und sagte: Nun, das find ich dumm!\n"
"			Juchhe! Juchhe!\n"
"			Juchheisa! Heisa! He!\n"
"			Seid nicht so ungezogen!\n"
"			Doch hurtig in dem Kreise ging's,\n"
"			Sie tanzten rechts, sie tanzten links,\n"
"			Und alle Roecke flogen.\n"
"			Sie wurden rot, sie wurden warm\n"
"			Und ruhten atmend Arm in Arm,\n"
"			Juchhe! Juchhe!\n"
"			Juchheisa! Heisa! He!\n"
"			Und Hueft an Ellenbogen.\n"
"			Und tu mir doch nicht so vertraut!\n"
"			Wie mancher hat nicht seine Braut\n"
"			Belogen und betrogen!\n"
"			Er schmeichelte sie doch bei Seit,\n"
"			Und von der Linde scholl es weit:\n"
"			Juchhe! Juchhe!\n"
"			Juchheisa! Heisa! He!\n"
"			Geschrei und Fiedelbogen.\n"
"Alter Bauer:\n"
"Herr Doktor, das ist schoen von Euch,\n"
"Dass Ihr uns heute nicht verschmaeht,\n"
"Und unter dieses Volksgedraeng,\n"
"Als ein so Hochgelahrter, geht.\n"
"So nehmet auch den schoensten Krug,\n"
"Den wir mit frischem Trunk gefuellt,\n"
"Ich bring ihn zu und wuensche laut,\n"
"Dass er nicht nur den Durst Euch stillt:\n"
"Die Zahl der Tropfen, die er hegt,\n"
"Sei Euren Tagen zugelegt.\n"
"Faust:\n"
"Ich nehme den Erquickungstrank\n"
"Erwidr' euch allen Heil und Dank.\n"
"(Das Volk sammelt sich im Kreis umher.)\n"
"Alter Bauer:\n"
"Fuerwahr, es ist sehr wohl getan,\n"
"Dass Ihr am frohen Tag erscheint;\n"
"Habt Ihr es vormals doch mit uns\n"
"An boesen Tagen gut gemeint!\n"
"Gar mancher steht lebendig hier\n"
"Den Euer Vater noch zuletzt\n"
"Der heissen Fieberwut entriss,\n"
"Als er der Seuche Ziel gesetzt.\n"
"Auch damals Ihr, ein junger Mann,\n"
"Ihr gingt in jedes Krankenhaus,\n"
"Gar manche Leiche trug man fort,\n"
"Ihr aber kamt gesund heraus,\n"
"Bestandet manche harte Proben;\n"
"Dem Helfer half der Helfer droben.\n"
"Alle:\n"
"Gesundheit dem bewaehrten Mann,\n"
"Dass er noch lange helfen kann!\n"
"Faust:\n"
"Vor jenem droben steht gebueckt,\n"
"Der helfen lehrt und Huelfe schickt.\n"
"Er geht mit Wagnern weiter.\n"
"Wagner:\n"
"Welch ein Gefuehl musst du, o grosser Mann,\n"
"Bei der Verehrung dieser Menge haben!\n"
"O gluecklich, wer von seinen Gaben\n"
"Solch einen Vorteil ziehen kann!\n"
"Der Vater zeigt dich seinem Knaben,\n"
"Ein jeder fragt und draengt und eilt,\n"
"Die Fiedel stockt, der Taenzer weilt.\n"
"Du gehst, in Reihen stehen sie,\n"
"Die Muetzen fliegen in die Hoeh;\n"
"Und wenig fehlt, so beugten sich die Knie,\n"
"Als kaem das Venerabile.\n"
"Faust:\n"
"Nur wenig Schritte noch hinauf zu jenem Stein,\n"
"Hier wollen wir von unsrer Wandrung rasten.\n"
"Hier sass ich oft gedankenvoll allein\n"
"Und quaelte mich mit Beten und mit Fasten.\n"
"An Hoffnung reich, im Glauben fest,\n"
"Mit Traenen, Seufzen, Haenderingen\n"
"Dacht ich das Ende jener Pest\n"
"Vom Herrn des Himmels zu erzwingen.\n"
"Der Menge Beifall toent mir nun wie Hohn.\n"
"O koenntest du in meinem Innern lesen,\n"
"Wie wenig Vater und Sohn\n"
"Solch eines Ruhmes wert gewesen!\n"
"Mein Vater war ein dunkler Ehrenmann,\n"
"Der ueber die Natur und ihre heil'gen Kreise\n"
"In Redlichkeit, jedoch auf seine Weise,\n"
"Mit grillenhafter Muehe sann;\n"
"Der, in Gesellschaft von Adepten,\n"
"Sich in die schwarze Kueche schloss,\n"
"Und, nach unendlichen Rezepten,\n"
"Das Widrige zusammengoss.\n"
"Da ward ein roter Leu, ein kuehner Freier,\n"
"Im lauen Bad der Lilie vermaehlt,\n"
"Und beide dann mit offnem Flammenfeuer\n"
"Aus einem Brautgemach ins andere gequaelt.\n"
"Erschien darauf mit bunten Farben\n"
"Die junge Koenigin im Glas,\n"
"Hier war die Arzenei, die Patienten starben,\n"
"Und niemand fragte: wer genas?\n"
"So haben wir mit hoellischen Latwergen\n"
"In diesen Taelern, diesen Bergen\n"
"Weit schlimmer als die Pest getobt.\n"
"Ich habe selbst den Gift an Tausende gegeben:\n"
"Sie welkten hin, ich muss erleben,\n"
"Dass man die frechen Moerder lobt.\n"
"Wagner:\n"
"Wie koennt Ihr Euch darum betrueben!\n"
"Tut nicht ein braver Mann genug,\n"
"Die Kunst, die man ihm uebertrug,\n"
"Gewissenhaft und puenktlich auszuueben?\n"
"Wenn du als Juengling deinen Vater ehrst,\n"
"So wirst du gern von ihm empfangen;\n"
"Wenn du als Mann die Wissenschaft vermehrst,\n"
"So kann dein Sohn zu hoehrem Ziel gelangen.\n"
"Faust:\n"
"O gluecklich, wer noch hoffen kann,\n"
"Aus diesem Meer des Irrtums aufzutauchen!\n"
"Was man nicht weiss, das eben brauchte man,\n"
"Und was man weiss, kann man nicht brauchen.\n"
"Doch lass uns dieser Stunde schoenes Gut\n"
"Durch solchen Truebsinn nicht verkuemmern!\n"
"Betrachte, wie in Abendsonne-Glut\n"
"Die gruenumgebnen Huetten schimmern.\n"
"Sie rueckt und weicht, der Tag ist ueberlebt,\n"
"Dort eilt sie hin und foerdert neues Leben.\n"
"O dass kein Fluegel mich vom Boden hebt\n"
"Ihr nach und immer nach zu streben!\n"
"Ich saeh im ewigen Abendstrahl\n"
"Die stille Welt zu meinen Fuessen,\n"
"Entzuendet alle Hoehn beruhigt jedes Tal,\n"
"Den Silberbach in goldne Stroeme fliessen.\n"
"Nicht hemmte dann den goettergleichen Lauf\n"
"Der wilde Berg mit allen seinen Schluchten;\n"
"Schon tut das Meer sich mit erwaermten Buchten\n"
"Vor den erstaunten Augen auf.\n"
"Doch scheint die Goettin endlich wegzusinken;\n"
"Allein der neue Trieb erwacht,\n"
"Ich eile fort, ihr ew'ges Licht zu trinken,\n"
"Vor mir den Tag und hinter mir die Nacht,\n"
"Den Himmel ueber mir und unter mir die Wellen.\n"
"Ein schoener Traum, indessen sie entweicht.\n"
"Ach! zu des Geistes Fluegeln wird so leicht\n"
"Kein koerperlicher Fluegel sich gesellen.\n"
"Doch ist es jedem eingeboren\n"
"Dass sein Gefuehl hinauf und vorwaerts dringt,\n"
"Wenn ueber uns, im blauen Raum verloren,\n"
"Ihr schmetternd Lied die Lerche singt;\n"
"Wenn ueber schroffen Fichtenhoehen\n"
"Der Adler ausgebreitet schwebt,\n"
"Und ueber Flaechen, ueber Seen\n"
"Der Kranich nach der Heimat strebt.\n"
"Wagner:\n"
"Ich hatte selbst oft grillenhafte Stunden,\n"
"Doch solchen Trieb hab ich noch nie empfunden.\n"
"Man sieht sich leicht an Wald und Feldern satt;\n"
"Des Vogels Fittich werd ich nie beneiden.\n"
"Wie anders tragen uns die Geistesfreuden\n"
"Von Buch zu Buch, von Blatt zu Blatt!\n"
"Da werden Winternaechte hold und schoen\n"
"Ein selig Leben waermet alle Glieder,\n"
"Und ach! entrollst du gar ein wuerdig Pergamen,\n"
"So steigt der ganze Himmel zu dir nieder.\n"
"Faust:\n"
"Du bist dir nur des einen Triebs bewusst,\n"
"O lerne nie den andern kennen!\n"
"Zwei Seelen wohnen, ach! in meiner Brust,\n"
"Die eine will sich von der andern trennen;\n"
"Die eine haelt, in derber Liebeslust,\n"
"Sich an die Welt mit klammernden Organen;\n"
"Die andre hebt gewaltsam sich vom Dust\n"
"Zu den Gefilden hoher Ahnen.\n"
"O gibt es Geister in der Luft,\n"
"Die zwischen Erd und Himmel herrschend weben\n"
"So steiget nieder aus dem goldnen Duft\n"
"Und fuehrt mich weg zu neuem, buntem Leben!\n"
"Ja, waere nur ein Zaubermantel mein,\n"
"Und trueg er mich in fremde Laender!\n"
"Mir sollt er um die koestlichsten Gewaender,\n"
"Nicht feil um einen Koenigsmantel sein.\n"
"Wagner:\n"
"Berufe nicht die wohlbekannte Schar,\n"
"Die stroemend sich im Dunstkreis ueberbreitet,\n"
"Dem Menschen tausendfaeltige Gefahr,\n"
"Von allen Enden her, bereitet.\n"
"Von Norden dringt der scharfe Geisterzahn\n"
"Auf dich herbei, mit pfeilgespitzten Zungen;\n"
"Von Morgen ziehn, vertrocknend, sie heran,\n"
"Und naehren sich von deinen Lungen;\n"
"Wenn sie der Mittag aus der Wueste schickt,\n"
"Die Glut auf Glut um deinen Scheitel haeufen\n"
"So bringt der West den Schwarm, der erst erquickt,\n"
"Um dich und Feld und Aue zu ersaeufen.\n"
"Sie hoeren gern, zum Schaden froh gewandt,\n"
"Gehorchen gern, weil sie uns gern betruegen;\n"
"Sie stellen wie vom Himmel sich gesandt,\n"
"Und lispeln englisch, wenn sie luegen.\n"
"Doch gehen wir! Ergraut ist schon die Welt,\n"
"Die Luft gekuehlt, der Nebel faellt!\n"
"Am Abend schaetzt man erst das Haus. –\n"
"Was stehst du so und blickst erstaunt hinaus?\n"
"Was kann dich in der Daemmrung so ergreifen?\n"
"Faust:\n"
"Siehst du den schwarzen Hund durch Saat und Stoppel streifen?\n"
"Wagner:\n"
"Ich sah ihn lange schon, nicht wichtig schien er mir.\n"
"Faust:\n"
"Betracht ihn recht! fuer was haeltst du das Tier?\n"
"Wagner:\n"
"Fuer einen Pudel, der auf seine Weise\n"
"Sich auf der Spur des Herren plagt.\n"
"Faust:\n"
"Bemerkst du, wie in weitem Schneckenkreise\n"
"Er um uns her und immer naeher jagt?\n"
"Und irr ich nicht, so zieht ein Feuerstrudel\n"
"Auf seinen Pfaden hinterdrein.\n"
"Wagner:\n"
"Ich sehe nichts als einen schwarzen Pudel;\n"
"Es mag bei Euch wohl Augentaeuschung sein.\n"
"Faust:\n"
"Mir scheint es, dass er magisch leise Schlingen\n"
"Zu kuenft'gem Band um unsre Fuesse zieht.\n"
"Wagner:\n"
"Ich seh ihn ungewiss und furchtsam uns umspringen,\n"
"Weil er, statt seines Herrn, zwei Unbekannte sieht.\n"
"Faust:\n"
"Der Kreis wird eng, schon ist er nah!\n"
"Wagner:\n"
"Du siehst! ein Hund, und kein Gespenst ist da.\n"
"Er knurrt und zweifelt, legt sich auf den Bauch,\n"
"Er wedelt. Alles Hundebrauch.\n"
"Faust:\n"
"Geselle dich zu uns! Komm hier!\n"
"Wagner:\n"
"Es ist ein pudelnaerrisch Tier.\n"
"Du stehest still, er wartet auf;\n"
"Du sprichst ihn an, er strebt an dir hinauf;\n"
"Verliere was, er wird es bringen,\n"
"Nach deinem Stock ins Wasser springen.\n"
"Faust:\n"
"Du hast wohl recht; ich finde nicht die Spur\n"
"Von einem Geist, und alles ist Dressur.\n"
"Wagner:\n"
"Dem Hunde, wenn er gut gezogen,\n"
"Wird selbst ein weiser Mann gewogen.\n"
"Ja, deine Gunst verdient er ganz und gar,\n"
"Er, der Studenten trefflicher Skolar.\n"
"(Sie gehen in das Stadttor.)";