//#include <iostream>
#include <algorithm>
#include <string>
#include "lowlist.h"
#define string std::string

string letters = "abcdefghijklmnopqrstuvwxyz";
string walloftext[26];

void caeserdecrypt(string original, int key)
{
    string letterswithkey = "";
    for (int i=0; i<26; i++)
        {
        letterswithkey += letters[(i+key)%26];
        }
    string result = "";
    for (char symbol : original)
    {
        if (letters.find(symbol) != string::npos)
        {
            result += letterswithkey[letters.find(symbol)];
        }
    }
    walloftext[key-1] = result;
    if (key < 26)
    {
        caeserdecrypt(original, (key+1));
    }
}

int checktext(string texttocheck)
{
    int amount = 0;
    string texttocheck2 = "";
    for (int i=0; i<50; i++)
    {
        texttocheck2 += texttocheck[i];
    }  
    for (string word : listofwords)
    {
        if (texttocheck2.find(word) != string::npos)
        {
            amount++;
        }
    }
    return amount;
}

int main() 
{
    int bestscore = 1;
    string endresult = "";
    string message = "Faust: Der Tragödie Erster Teil"
    "Nacht."
    "In einem hochgewölbten, engen gotischen Zimmer Faust, unruhig auf seinem Sessel am Pulte."
    "Faust:"
    "Habe nun, ach! Philosophie,"
    "Juristerei und Medizin,"
    "Und leider auch Theologie"
    "Durchaus studiert, mit heißem Bemühn."
    "Da steh ich nun, ich armer Tor!"
    "Und bin so klug als wie zuvor;"
    "Heiße Magister, heiße Doktor gar"
    "Und ziehe schon an die zehen Jahr"
    "Herauf, herab und quer und krumm"
    "Meine Schüler an der Nase herum –"
    "Und sehe, daß wir nichts wissen können!"
    "Das will mir schier das Herz verbrennen."
    "Zwar bin ich gescheiter als all die Laffen,"
    "Doktoren, Magister, Schreiber und Pfaffen;"
    "Mich plagen keine Skrupel noch Zweifel,"
    "Fürchte mich weder vor Hölle noch Teufel –"
    "Dafür ist mir auch alle Freud entrissen,"
    "Bilde mir nicht ein, was Rechts zu wissen,"
    "Bilde mir nicht ein, ich könnte was lehren,"
    "Die Menschen zu bessern und zu bekehren."
    "Auch hab ich weder Gut noch Geld,"
    "Noch Ehr und Herrlichkeit der Welt;"
    "Es möchte kein Hund so länger leben!"
    "Drum hab ich mich der Magie ergeben,"
    "Ob mir durch Geistes Kraft und Mund"
    "Nicht manch Geheimnis würde kund;"
    "Daß ich nicht mehr mit saurem Schweiß"
    "Zu sagen brauche, was ich nicht weiß;"
    "Daß ich erkenne, was die Welt"
    "Im Innersten zusammenhält,"
    "Schau alle Wirkenskraft und Samen,"
    "Und tu nicht mehr in Worten kramen."
    "O sähst du, voller Mondenschein,"
    "Zum letzenmal auf meine Pein,"
    "Den ich so manche Mitternacht"
    "An diesem Pult herangewacht:"
    "Dann über Büchern und Papier,"
    "Trübsel'ger Freund, erschienst du mir!"
    "Ach! könnt ich doch auf Bergeshöhn"
    "In deinem lieben Lichte gehn,"
    "Um Bergeshöhle mit Geistern schweben,"
    "Auf Wiesen in deinem Dämmer weben,"
    "Von allem Wissensqualm entladen,"
    "In deinem Tau gesund mich baden!"
    "Weh! steck ich in dem Kerker noch?"
    "Verfluchtes dumpfes Mauerloch,"
    "Wo selbst das liebe Himmelslicht"
    "Trüb durch gemalte Scheiben bricht!"
    "Beschränkt mit diesem Bücherhauf,"
    "den Würme nagen, Staub bedeckt,"
    "Den bis ans hohe Gewölb hinauf"
    "Ein angeraucht Papier umsteckt;"
    "Mit Gläsern, Büchsen rings umstellt,"
    "Mit Instrumenten vollgepfropft,"
    "Urväter Hausrat drein gestopft –"
    "Das ist deine Welt! das heißt eine Welt!"
    "Und fragst du noch, warum dein Herz"
    "Sich bang in deinem Busen klemmt?"
    "Warum ein unerklärter Schmerz"
    "Dir alle Lebensregung hemmt?"
    "Statt der lebendigen Natur,"
    "Da Gott die Menschen schuf hinein,"
    "Umgibt in Rauch und Moder nur"
    "Dich Tiergeripp und Totenbein."
    "Flieh! auf! hinaus ins weite Land!"
    "Und dies geheimnisvolle Buch,"
    "Von Nostradamus' eigner Hand,"
    "Ist dir es nicht Geleit genug?"
    "Erkennest dann der Sterne Lauf,"
    "Und wenn Natur dich Unterweist,"
    "Dann geht die Seelenkraft dir auf,"
    "Wie spricht ein Geist zum andren Geist."
    "Umsonst, daß trocknes Sinnen hier"
    "Die heil'gen Zeichen dir erklärt:"
    "Ihr schwebt, ihr Geister, neben mir;"
    "Antwortet mir, wenn ihr mich hört!"
    "(Er schlägt das Buch auf und erblickt das Zeichen des Makrokosmus.)"
    "Ha! welche Wonne fließt in diesem Blick"
    "Auf einmal mir durch alle meine Sinnen!"
    "Ich fühle junges, heil'ges Lebensglück"
    "Neuglühend mir durch Nerv' und Adern rinnen."
    "War es ein Gott, der diese Zeichen schrieb,"
    "Die mir das innre Toben stillen,"
    "Das arme Herz mit Freude füllen,"
    "Und mit geheimnisvollem Trieb"
    "Die Kräfte der Natur rings um mich her enthüllen?"
    "Bin ich ein Gott? Mir wird so licht!"
    "Ich schau in diesen reinen Zügen"
    "Die wirkende Natur vor meiner Seele liegen."
    "Jetzt erst erkenn ich, was der Weise spricht:"
    "Die Geisterwelt ist nicht verschlossen;"
    "Dein Sinn ist zu, dein Herz ist tot!"
    "Auf, bade, Schüler, unverdrossen"
    "Die ird'sche Brust im Morgenrot!"
    "(er beschaut das Zeichen.)"
    "Wie alles sich zum Ganzen webt,"
    "Eins in dem andern wirkt und lebt!"
    "Wie Himmelskräfte auf und nieder steigen"
    "Und sich die goldnen Eimer reichen!"
    "Mit segenduftenden Schwingen"
    "Vom Himmel durch die Erde dringen,"
    "Harmonisch all das All durchklingen!"
    "Welch Schauspiel! Aber ach! ein Schauspiel nur!"
    "Wo fass ich dich, unendliche Natur?"
    "Euch Brüste, wo? Ihr Quellen alles Lebens,"
    "An denen Himmel und Erde hängt,"
    "Dahin die welke Brust sich drängt –"
    "Ihr quellt, ihr tränkt, und schmacht ich so vergebens?"
    "(er schlägt unwillig das Buch um und erblickt das Zeichen des Erdgeistes.)"
    "Wie anders wirkt dies Zeichen auf mich ein!"
    "Du, Geist der Erde, bist mir näher;"
    "Schon fühl ich meine Kräfte höher,"
    "Schon glüh ich wie von neuem Wein."
    "Ich fühle Mut, mich in die Welt zu wagen,"
    "Der Erde Weh, der Erde Glück zu tragen,"
    "Mit Stürmen mich herumzuschlagen"
    "Und in des Schiffbruchs Knirschen nicht zu zagen."
    "Es wölkt sich über mir –"
    "Der Mond verbirgt sein Licht –"
    "Die Lampe schwindet!"
    "Es dampft! Es zucken rote Strahlen"
    "Mir um das Haupt – Es weht"
    "Ein Schauer vom Gewölb herab"
    "Und faßt mich an!"
    "Ich fühl's, du schwebst um mich, erflehter Geist"
    "Enthülle dich!"
    "Ha! wie's in meinem Herzen reißt!"
    "Zu neuen Gefühlen"
    "All meine Sinnen sich erwühlen!"
    "Ich fühle ganz mein Herz dir hingegeben!"
    "Du mußt! du mußt! und kostet es mein Leben!"
    "(Er faßt das Buch und spricht das Zeichen des Geistes geheimnisvoll aus. Es zuckt eine rötliche Flamme, der Geist erscheint in der Flamme.)"
    "Geist:"
    "Wer ruft mir?"
    "Faust (abgewendet):"
    "			Schreckliches Gesicht!"
    "Geist:"
    "Du hast mich mächtig angezogen,"
    "An meiner Sphäre lang gesogen,"
    "Und nun –"
    "Faust:"
    "			Weh! ich ertrag dich nicht!"
    "Geist:"
    "Du flehst, eratmend mich zu schauen,"
    "Meine Stimme zu hören, mein Antlitz zu sehn;"
    "Mich neigt dein mächtig Seelenflehn,"
    "Da bin ich! – Welch erbärmlich Grauen"
    "Faßt Übermenschen dich! Wo ist der Seele Ruf?"
    "Wo ist die Brust, die eine Welt in sich erschuf"
    "Und trug und hegte, die mit Freudebeben"
    "Erschwoll, sich uns, den Geistern, gleich zu heben?"
    "Wo bist du, Faust, des Stimme mir erklang,"
    "Der sich an mich mit allen Kräften drang?"
    "Bist du es, der, von meinem Hauch umwittert,"
    "In allen Lebenslagen zittert,"
    "Ein furchtsam weggekrümmter Wurm?"
    "Faust:"
    "Soll ich dir, Flammenbildung, weichen?"
    "Ich bin's, bin Faust, bin deinesgleichen!"
    "Geist:"
    "In Lebensfluten, im Tatensturm"
    "Wall ich auf und ab,"
    "Wehe hin und her!"
    "Geburt und Grab,"
    "Ein ewiges Meer,"
    "Ein wechselndes Wehen,"
    "Ein glühend Leben,"
    "So schaff ich am laufenden Webstuhl der Zeit"
    "Und wirke der Gottheit lebendiges Kleid."
    "Faust:"
    "Der du die weite Welt umschweifst,"
    "Geschäftiger Geist, wie nah fühl ich mich dir!"
    "Geist:"
    "Du gleichst dem Geist, den du begreifst,"
    "Nicht mir!"
    "(verschwindet)"
    "Faust (zusammenstürzend) :"
    "Nicht dir?"
    "Wem denn?"
    "Ich Ebenbild der Gottheit!"
    "Und nicht einmal dir!"
    "(es klopft)"
    "O Tod! ich kenn's – das ist mein Famulus –"
    "Es wird mein schönstes Glück zunichte!"
    "Daß diese Fülle der Geschichte"
    "Der trockne Schleicher stören muß!"
    "Wagner im Schlafrock und der Nachtmütze, eine Lampe in der Hand. Faust wendet sich unwillig."
    "Wagner:"
    "Verzeiht! ich hör euch deklamieren;"
    "Ihr last gewiß ein griechisch Trauerspiel?"
    "In dieser Kunst möcht ich was profitieren,"
    "Denn heutzutage wirkt das viel."
    "Ich hab es öfters rühmen hören,"
    "Ein Komödiant könnt einen Pfarrer lehren."
    "Faust:"
    "Ja, wenn der Pfarrer ein Komödiant ist;"
    "Wie das denn wohl zuzeiten kommen mag."
    "Wagner:"
    "Ach! wenn man so in sein Museum gebannt ist,"
    "Und sieht die Welt kaum einen Feiertag,"
    "Kaum durch ein Fernglas, nur von weitem,"
    "Wie soll man sie durch Überredung leiten?"
    "Faust:"
    "Wenn ihr's nicht fühlt, ihr werdet's nicht erjagen,"
    "Wenn es nicht aus der Seele dringt"
    "Und mit urkräftigem Behagen"
    "Die Herzen aller Hörer zwingt."
    "Sitzt ihr nur immer! leimt zusammen,"
    "Braut ein Ragout von andrer Schmaus"
    "Und blast die kümmerlichen Flammen"
    "Aus eurem Aschenhäuschen 'raus!"
    "Bewundrung von Kindern und Affen,"
    "Wenn euch darnach der Gaumen steht –"
    "Doch werdet ihr nie Herz zu Herzen schaffen,"
    "Wenn es euch nicht von Herzen geht."
    "Wagner:"
    "Allein der Vortrag macht des Redners Glück;"
    "Ich fühl es wohl, noch bin ich weit zurück."
    "Faust:"
    "Such Er den redlichen Gewinn!"
    "Sei Er kein schellenlauter Tor!"
    "Es trägt Verstand und rechter Sinn"
    "Mit wenig Kunst sich selber vor!"
    "Und wenn's euch Ernst ist, was zu sagen,"
    "Ist's nötig, Worten nachzujagen?"
    "Ja, eure Reden, die so blinkend sind,"
    "In denen ihr der Menschheit Schnitzel kräuselt,"
    "Sind unerquicklich wie der Nebelwind,"
    "Der herbstlich durch die dürren Blätter säuselt!"
    "Wagner:"
    "Ach Gott! die Kunst ist lang;"
    "Und kurz ist unser Leben."
    "Mir wird, bei meinem kritischen Bestreben,"
    "Doch oft um Kopf und Busen bang."
    "Wie schwer sind nicht die Mittel zu erwerben,"
    "Durch die man zu den Quellen steigt!"
    "Und eh man nur den halben Weg erreicht,"
    "Muß wohl ein armer Teufel sterben."
    "Faust:"
    "Das Pergament, ist das der heil'ge Bronnen,"
    "Woraus ein Trunk den Durst auf ewig stillt?"
    "Erquickung hast du nicht gewonnen,"
    "Wenn sie dir nicht aus eigner Seele quillt."
    "Wagner:"
    "Verzeiht! es ist ein groß Ergetzen,"
    "Sich in den Geist der Zeiten zu versetzen;"
    "Zu schauen, wie vor uns ein weiser Mann gedacht,"
    "Und wie wir's dann zuletzt so herrlich weit gebracht."
    "Faust:"
    "O ja, bis an die Sterne weit!"
    "Mein Freund, die Zeiten der Vergangenheit"
    "Sind uns ein Buch mit sieben Siegeln."
    "Was ihr den Geist der Zeiten heißt,"
    "Das ist im Grund der Herren eigner Geist,"
    "In dem die Zeiten sich bespiegeln."
    "Da ist's denn wahrlich oft ein Jammer!"
    "Man läuft euch bei dem ersten Blick davon."
    "Ein Kehrichtfaß und eine Rumpelkammer"
    "Und höchstens eine Haupt- und Staatsaktion"
    "Mit trefflichen pragmatischen Maximen,"
    "Wie sie den Puppen wohl im Munde ziemen!"
    "Wagner:"
    "Allein die Welt! des Menschen Herz und Geist!"
    "Möcht jeglicher doch was davon erkennen."
    "Faust:"
    "Ja, was man so erkennen heißt!"
    "Wer darf das Kind beim Namen nennen?"
    "Die wenigen, die was davon erkannt,"
    "Die töricht g'nug ihr volles Herz nicht wahrten,"
    "Dem Pöbel ihr Gefühl, ihr Schauen offenbarten,"
    "Hat man von je gekreuzigt und verbrannt."
    "Ich bitt Euch, Freund, es ist tief in der Nacht,"
    "Wir müssen's diesmal unterbrechen."
    "Wagner:"
    "Ich hätte gern nur immer fortgewacht,"
    "Um so gelehrt mit Euch mich zu besprechen."
    "Doch morgen, als am ersten Ostertage,"
    "Erlaubt mir ein' und andre Frage."
    "Mit Eifer hab' ich mich der Studien beflissen;"
    "Zwar weiß ich viel, doch möcht' ich alles wissen."
    "(Ab.)"
    "Faust (allein):"
    "Wie nur dem Kopf nicht alle Hoffnung schwindet,"
    "Der immerfort an schalem Zeuge klebt,"
    "Mit gier'ger Hand nach Schätzen gräbt,"
    "Und froh ist, wenn er Regenwürmer findet!"
    "Darf eine solche Menschenstimme hier,"
    "Wo Geisterfülle mich umgab, ertönen?"
    "Doch ach! für diesmal dank ich dir,"
    "Dem ärmlichsten von allen Erdensöhnen."
    "Du rittest mich von der Verzweiflung los,"
    "Die mir die Sinne schon zerstören wollte."
    "Ach! die Erscheinung war so riesengroß,"
    "Daß ich mich recht als Zwerg empfinden sollte."
    "Ich, Ebenbild der Gottheit, das sich schon"
    "Ganz nah gedünkt dem Spiegel ew'ger Wahrheit,"
    "Sein selbst genoß in Himmelsglanz und Klarheit,"
    "Und abgestreift den Erdensohn;"
    "Ich, mehr als Cherub, dessen freie Kraft"
    "Schon durch die Adern der Natur zu fließen"
    "Und, schaffend, Götterleben zu genießen"
    "Sich ahnungsvoll vermaß, wie muß ich's büßen!"
    "Ein Donnerwort hat mich hinweggerafft."
    "Nicht darf ich dir zu gleichen mich vermessen;"
    "Hab ich die Kraft dich anzuziehn besessen,"
    "So hatt ich dich zu halten keine Kraft."
    "Zu jenem sel'gen Augenblicke"
    "Ich fühlte mich so klein, so groß;"
    "Du stießest grausam mich zurück,"
    "Ins ungewisse Menschenlos."
    "Wer lehret mich? was soll ich meiden?"
    "Soll ich gehorchen jenem Drang?"
    "Ach! unsre Taten selbst, so gut als unsre Leiden,"
    "Sie hemmen unsres Lebens Gang."
    "Dem Herrlichsten, was auch der Geist empfangen,"
    "Drängt immer fremd und fremder Stoff sich an;"
    "Wenn wir zum Guten dieser Welt gelangen,"
    "Dann heißt das Beßre Trug und Wahn."
    "Die uns das Leben gaben, herrliche Gefühle"
    "Erstarren in dem irdischen Gewühle."
    "Wenn Phantasie sich sonst mit kühnem Flug"
    "Und hoffnungsvoll zum Ewigen erweitert,"
    "So ist ein kleiner Raum ihr genug,"
    "Wenn Glück auf Glück im Zeitenstrudel scheitert."
    "Die Sorge nistet gleich im tiefen Herzen,"
    "Dort wirket sie geheime Schmerzen,"
    "Unruhig wiegt sie sich und störet Luft und Ruh;"
    "Sie deckt sich stets mit neuen Masken zu,"
    "Sie mag als Haus und Hof, als Weib und Kind erscheinen,"
    "Als Feuer, Wasser, Dolch und Gift;"
    "Du bebst vor allem, was nicht trifft,"
    "Und was du nie verlierst, das mußt du stets beweinen."
    "Den Göttern gleich ich nicht! zu tief ist es gefühlt;"
    "Dem Wurme gleich ich, der den Staub durchwühlt,"
    "Den, wie er sich im Staube nährend lebt,"
    "Des Wandrers Tritt vernichtet und begräbt."
    "Ist es nicht Staub, was diese hohe Wand"
    "Aus hundert Fächern mit verenget?"
    "Der Trödel, der mit tausendfachem Tand"
    "In dieser Mottenwelt mich dränget?"
    "Hier soll ich finden, was mir fehlt?"
    "Soll ich vielleicht in tausend Büchern lesen,"
    "Daß überall die Menschen sich gequält,"
    "Daß hie und da ein Glücklicher gewesen? –"
    "Was grinsest du mir, hohler Schädel, her?"
    "Als daß dein Hirn, wie meines, einst verwirret"
    "Den leichten Tag gesucht und in der Dämmrung schwer,"
    "Mit Luft nach Wahrheit, jämmerlich geirret."
    "Ihr Instrumente freilich spottet mein,"
    "Mit Rad und Kämmen, Walz und Bügel:"
    "Ich stand am Tor, ihr solltet Schlüssel sein;"
    "Zwar euer Bart ist kraus, doch hebt ihr nicht die Riegel."
    "Geheimnisvoll am lichten Tag"
    "Läßt sich Natur des Schleiers nicht berauben,"
    "Und was sie deinem Geist nicht offenbaren mag,"
    "Das zwingst du ihr nicht ab mit Hebeln und mit Schrauben."
    "Du alt Geräte, das ich nicht gebraucht,"
    "Du stehst nur hier, weil dich mein Vater brauchte."
    "Du alte Rolle, du wirst angeraucht,"
    "Solang an diesem Pult die trübe Lampe schmauchte."
    "Weit besser hätt ich doch mein Weniges verpraßt,"
    "Als mit dem Wenigen belastet hier zu schwitzen!"
    "Was du ererbt von deinem Vater hast,"
    "Erwirb es, um es zu besitzen."
    "Was man nicht nützt, ist eine schwere Last,"
    "Nur was der Augenblick erschafft, das kann er nützen."
    "Doch warum heftet sich mein Blick auf jene Stelle?"
    "Ist jenes Fläschchen dort den Augen ein Magnet?"
    "Warum wird mir auf einmal lieblich helle,"
    "Als wenn im nächt'gen Wald uns Mondenglanz umweht?"
    "Ich grüße dich, du einzige Phiole,"
    "Die ich mit Andacht nun herunterhole!"
    "In dir verehr ich Menschenwitz und Kunst."
    "Du Inbegriff der holden Schlummersäfte,"
    "Du Auszug aller tödlich feinen Kräfte,"
    "Erweise deinem Meister deine Gunst!"
    "Ich sehe dich, es wird der Schmerz gelindert,"
    "Ich fasse dich, das Streben wird gemindert,"
    "Des Geistes Flutstrom ebbet nach und nach."
    "Ins hohe Meer werd ich hinausgewiesen,"
    "Die Spiegelflut erglänzt zu meinen Füßen,"
    "Zu neuen Ufern lockt ein neuer Tag."
    "Ein Feuerwagen schwebt, auf leichten Schwingen,"
    "An mich heran! Ich fühle mich bereit,"
    "Auf neuer Bahn den Äther zu durchdringen,"
    "Zu neuen Sphären reiner Tätigkeit."
    "Dies hohe Leben, diese Götterwonne!"
    "Du, erst noch Wurm, und die verdienest du?"
    "Ja, kehre nur der holden Erdensonne"
    "Entschlossen deinen Rücken zu!"
    "Vermesse dich, die Pforten aufzureißen,"
    "Vor denen jeder gern vorüberschleicht!"
    "Hier ist es Zeit, durch Taten zu beweisen,"
    "Das Manneswürde nicht der Götterhöhe weicht,"
    "Vor jener dunkeln Höhle nicht zu beben,"
    "In der sich Phantasie zu eigner Qual verdammt,"
    "Nach jenem Durchgang hinzustreben,"
    "Um dessen engen Mund die ganze Hölle flammt;"
    "In diesem Schritt sich heiter zu entschließen,"
    "Und wär es mit Gefahr, ins Nichts dahin zu fließen."
    "Nun komm herab, kristallne reine Schale!"
    "Hervor aus deinem alten Futterale,"
    "An die ich viele Jahre nicht gedacht!"
    "Du glänzetst bei der Väter Freudenfeste,"
    "Erheitertest die ernsten Gäste,"
    "Wenn einer dich dem andern zugebracht."
    "Der vielen Bilder künstlich reiche Pracht,"
    "Des Trinkers Pflicht, sie reimweis zu erklären,"
    "Auf einen Zug die Höhlung auszuleeren,"
    "Erinnert mich an manche Jugendnacht."
    "Ich werde jetzt dich keinem Nachbar reichen,"
    "Ich werde meinen Witz an deiner Kunst nicht zeigen."
    "Hier ist ein Saft, der eilig trunken macht;"
    "Mit brauner Flut erfüllt er deine Höhle."
    "Den ich bereit, den ich wähle,"
    "Der letzte Trunk sei nun, mit ganzer Seele,"
    "Als festlich hoher Gruß, dem Morgen zugebracht!"
    "(Er setzt die Schale an den Mund.)"
    "Glockenklang und Chorgesang."
    "Chor der Engel:"
    "			Christ ist erstanden!"
    "			Freude dem Sterblichen,"
    "			Den die verderblichen,"
    "			Schleichenden, erblichen"
    "			Mängel unwanden."
    "Faust:"
    "Welch tiefes Summen, welch heller Ton"
    "Zieht mit Gewalt das Glas von meinem Munde?"
    "Verkündigt ihr dumpfen Glocken schon"
    "Des Osterfestes erste Feierstunde?"
    "Ihr Chöre, singt ihr schon den tröstlichen Gesang,"
    "Der einst, um Grabes Nacht, von Engelslippen klang,"
    "Gewißheit einem neuen Bunde?"
    "Chor der Weiber:"
    "			Mit Spezereien"
    "			Hatten wir ihn gepflegt,"
    "			Wir seine Treuen"
    "			Hatten ihn hingelegt;"
    "			Tücher und Binden"
    "			Reinlich unwanden wir,"
    "			Ach! und wir finden"
    "			Christ nicht mehr hier."
    "Chor der Engel:"
    "			Christ ist erstanden!"
    "			Selig der Liebende,"
    "			Der die betrübende,"
    "			Heilsam und übende"
    "			Prüfung bestanden."
    "Faust:"
    "Was sucht ihr, mächtig und gelind,"
    "Ihr Himmelstöne, mich am Staube?"
    "Klingt dort umher, wo weiche Menschen sind."
    "Die Botschaft hör ich wohl, allein mir fehlt der Glaube;"
    "Das Wunder ist des Glaubens liebstes Kind."
    "Zu jenen Sphären wag ich nicht zu streben,"
    "Woher die holde Nachricht tönt;"
    "Und doch, an diesen Klang von Jugend auf gewöhnt,"
    "Ruft er auch jetzt zurück mich in das Leben."
    "Sonst stürzte sich der Himmelsliebe Kuß"
    "Auf mich herab in ernster Sabbatstille;"
    "Da klang so ahnungsvoll des Glockentones Fülle,"
    "Und ein Gebet war brünstiger Genuß;"
    "Ein unbegreiflich holdes Sehnen"
    "Trieb mich, durch Wald und Wiesen hinzugehn,"
    "Und unter tausend heißen Tränen"
    "Fühlt ich mir eine Welt entstehn."
    "Dies Lieb verkündete der Jugend muntre Spiele,"
    "Der Frühlingsfeier freies Glück;"
    "Erinnrung hält mich nun, mit kindlichem Gefühle,"
    "Vom letzten, ernsten Schritt zurück."
    "O tönet fort, ihr süßen Himmelslieder!"
    "Die Träne quillt, die Erde hat mich wieder!"
    "Chor der Jünger:"
    "			Hat der Begrabene"
    "			Schon sich nach oben,"
    "			Lebend Erhabene,"
    "			Herrlich erhoben;"
    "			Ist er in Werdeluft"
    "			Schaffender Freude nah:"
    "			Ach! an der Erde Brust"
    "			Sind wir zum Leide da."
    "			Ließ er die Seinen"
    "			Schmachtend uns hier zurück;"
    "			Ach! wir beweinen,"
    "			Meister, dein Glück!"
    "Chor der Engel:"
    "			Christ ist erstanden,"
    "			Aus der Verwesung Schoß."
    "			Reißet von Banden"
    "			Freudig euch los!"
    "			Tätig ihn preisenden,"
    "			Liebe beweisenden,"
    "			Brüderlich speisenden,"
    "			Predigend reisenden,"
    "			Wonne verheißenden"
    "			Euch ist der Meister nah,"
    "			Euch ist er da!"
    "			Vor dem Tor"
    "Spaziergänger aller Art ziehen hinaus."
    "Einige Handwerksbursche:"
    "Warum denn dort hinaus?"
    "Andre:"
    "Wir gehn hinaus aufs Jägerhaus."
    "Die Ersten:"
    "Wir aber wollen nach der Mühle wandern."
    "Ein Handwerksbursch:"
    "Ich rat euch, nach dem Wasserhof zu gehn."
    "Zweiter:"
    "Der Weg dahin ist gar nicht schön."
    "Die Zweiten:"
    "Was tust denn du?"
    "Ein Dritter:"
    "			Ich gehe mit den andern."
    "Vierter:"
    "Nach Burgdorf kommt herauf, gewiß dort findet ihr"
    "Die schönsten Mädchen und das beste Bier,"
    "Und Händel von der ersten Sorte."
    "Fünfter:"
    "Du überlustiger Gesell,"
    "Juckt dich zum drittenmal das Fell?"
    "Ich mag nicht hin, mir graut es vor dem Orte."
    "Dienstmädchen:"
    "Nein, nein! ich gehe nach der Stadt zurück."
    "Andre:"
    "Wir finden ihn gewiß bei jenen Pappeln stehen."
    "Erste:"
    "Das ist für mich kein großes Glück;"
    "Er wird an deiner Seite gehen,"
    "Mit dir nur tanzt er auf dem Plan."
    "Was gehn mich deine Freuden an!"
    "Andre:"
    "Heut ist er sicher nicht allein,"
    "Der Krauskopf, sagt er, würde bei ihm sein."
    "Schüler:"
    "Blitz, wie die wackern Dirnen schreiten!"
    "Herr Bruder, komm! wir müssen sie begleiten."
    "Ein starkes Bier, ein beizender Toback,"
    "Und eine Magd im Putz, das ist nun mein Geschmack."
    "Bürgermädchen:"
    "Da sieh mir nur die schönen Knaben!"
    "Es ist wahrhaftig eine Schmach:"
    "Gesellschaft könnten sie die allerbeste haben,"
    "Und laufen diesen Mägden nach!"
    "Zweiter Schüler (zum ersten):"
    "Nicht so geschwind! dort hinten kommen zwei,"
    "Sie sind gar niedlich angezogen,"
    "'s ist meine Nachbarin dabei;"
    "Ich bin dem Mädchen sehr gewogen."
    "Sie gehen ihren stillen Schritt"
    "Und nehmen uns doch auch am Ende mit."
    "Erster:"
    "Herr Bruder, nein! Ich bin nicht gern geniert."
    "Geschwind! daß wir das Wildbret nicht verlieren."
    "Die Hand, die samstags ihren Besen führt"
    "Wird sonntags dich am besten karessieren."
    "Bürger:"
    "Nein, er gefällt mir nicht, der neue Burgemeister!"
    "Nun, da er's ist, wird er nur täglich dreister."
    "Und für die Stadt was tut denn er?"
    "Wird es nicht alle Tage schlimmer?"
    "Gehorchen soll man mehr als immer,"
    "Und zahlen mehr als je vorher."
    "Bettler (singt):"
    "			Ihr guten Herrn, ihr schönen Frauen,"
    "			So wohlgeputzt und backenrot,"
    "			Belieb es euch, mich anzuschauen,"
    "			Und seht und mildert meine Not!"
    "			Laßt hier mich nicht vergebens leiern!"
    "			Nur der ist froh, der geben mag."
    "			Ein Tag, den alle Menschen feiern,"
    "			Er sei für mich ein Erntetag."
    "Andrer Bürger:"
    "Nichts Bessers weiß ich mir an Sonn- und Feiertagen"
    "Als ein Gespräch von Krieg und Kriegsgeschrei,"
    "Wenn hinten, weit, in der Türkei,"
    "Die Völker aufeinander schlagen."
    "Man steht am Fenster, trinkt sein Gläschen aus"
    "Und sieht den Fluß hinab die bunten Schiffe gleiten;"
    "Dann kehrt man abends froh nach Haus,"
    "Und segnet Fried und Friedenszeiten."
    "Dritter Bürger:"
    "Herr Nachbar, ja! so laß ich's auch geschehn:"
    "Sie mögen sich die Köpfe spalten,"
    "Mag alles durcheinander gehn;"
    "Doch nur zu Hause bleib's beim alten."
    "Alte (zu den Bürgermädchen):"
    "Ei! wie geputzt! das schöne junge Blut!"
    "Wer soll sich nicht in euch vergaffen? –"
    "Nur nicht so stolz! es ist schon gut!"
    "Und was ihr wünscht, das wüßt ich wohl zu schaffen."
    "Bürgermädchen:"
    "Agathe, fort! ich nehme mich in acht,"
    "Mit solchen Hexen öffentlich zu gehen;"
    "Sie ließ mich zwar in Sankt Andreas' Nacht"
    "Den künft'gen Liebsten leiblich sehen –"
    "Die Andre:"
    "Mir zeigte sie ihn im Kristall,"
    "Soldatenhaft, mit mehreren Verwegnen;"
    "Ich seh mich um, ich such ihn überall,"
    "Allein mir will er nicht begegnen."
    "Soldaten:"
    "			Burgen mit hohen"
    "			Mauern und Zinnen,"
    "			Mädchen mit stolzen"
    "			Höhnenden Sinnen"
    "			Möcht ich gewinnen!"
    "			Kühn ist das Mühen,"
    "			Herrlich der Lohn!"
    "			Und die Trompete"
    "			Lassen wir werben,"
    "			Wie zu der Freude,"
    "			So zum Verderben."
    "			Das ist ein Stürmen!"
    "			Das ist ein Leben!"
    "			Mädchen und Burgen"
    "			Müssen sich geben."
    "			Kühn ist das Mühen,"
    "			Herrlich der Lohn!"
    "			Und die Soldaten"
    "			Ziehen davon."
    "Faust und Wagner."
    "Faust:"
    "Vom Eise befreit sind Strom und Bäche"
    "Durch des Frühlings holden, belebenden Blick;"
    "Im Tale grünet Hoffnungsglück;"
    "Der alte Winter, in seiner Schwäche,"
    "Zog sich in rauhe Berge zurück."
    "Von dorther sendet er, fliehend, nur"
    "Ohnmächtige Schauer kornigen Eises"
    "In Streifen über die grünende Flur;"
    "Aber die Sonne duldet kein Weißes,"
    "Überall regt sich Bildung und Streben,"
    "Alles will sie mit Farben beleben;"
    "Doch an Blumen fehlt's im Revier"
    "Sie nimmt geputzte Menschen dafür."
    "Kehre dich um, von diesen Höhen"
    "Nach der Stadt zurückzusehen."
    "Aus dem hohlen finstern Tor"
    "Dringt ein buntes Gewimmel hervor."
    "Jeder sonnt sich heute so gern."
    "Sie feiern die Auferstehung des Herrn,"
    "Denn sie sind selber auferstanden,"
    "Aus niedriger Häuser dumpfen Gemächern,"
    "Aus Handwerks- und Gewerbesbanden,"
    "Aus dem Druck von Giebeln und Dächern,"
    "Aus der Straßen quetschender Enge,"
    "Aus der Kirchen ehrwürdiger Nacht"
    "Sind sie alle ans Licht gebracht."
    "Sieh nur, sieh! wie behend sich die Menge"
    "Durch die Gärten und Felder zerschlägt,"
    "Wie der Fluß, in Breit und Länge"
    "So manchen lustigen Nachen bewegt,"
    "Und bis zum Sinken überladen"
    "Entfernt sich dieser letzte Kahn."
    "Selbst von des Berges fernen Pfaden"
    "Blinken uns farbige Kleider an."
    "Ich höre schon des Dorfs Getümmel,"
    "Hier ist des Volkes wahrer Himmel,"
    "Zufrieden jauchzet groß und klein:"
    "Hier bin ich Mensch, hier darf ich's sein!"
    "Wagner:"
    "Mit Euch, Herr Doktor, zu spazieren"
    "Ist ehrenvoll und ist Gewinn;"
    "Doch würd ich nicht allein mich her verlieren,"
    "Weil ich ein Feind von allem Rohen bin."
    "Das Fiedeln, Schreien, Kegelschieben"
    "Ist mir ein gar verhaßter Klang;"
    "Sie toben wie vom bösen Geist getrieben"
    "Und nennen's Freude. nennen's Gesang."
    "Bauern unter der Linde."
    "Tanz und Gesang."
    "			Der Schäfer putzte sich zum Tanz,"
    "			Mit bunter Jacke, Band und Kranz,"
    "			Schmuck war er angezogen."
    "			Schon um die Linde war es voll,"
    "			Und alles tanzte schon wie toll."
    "			Juchhe! Juchhe!"
    "			Juchheisa! Heisa! He!"
    "			So ging der Fiedelbogen."
    "			Er drückte hastig sich heran,"
    "			Da stieß er an ein Mädchen an"
    "			Mit seinem Ellenbogen;"
    "			Die frische Dirne kehrt, sich um"
    "			Und sagte: Nun, das find ich dumm!"
    "			Juchhe! Juchhe!"
    "			Juchheisa! Heisa! He!"
    "			Seid nicht so ungezogen!"
    "			Doch hurtig in dem Kreise ging's,"
    "			Sie tanzten rechts, sie tanzten links,"
    "			Und alle Röcke flogen."
    "			Sie wurden rot, sie wurden warm"
    "			Und ruhten atmend Arm in Arm,"
    "			Juchhe! Juchhe!"
    "			Juchheisa! Heisa! He!"
    "			Und Hüft an Ellenbogen."
    "			Und tu mir doch nicht so vertraut!"
    "			Wie mancher hat nicht seine Braut"
    "			Belogen und betrogen!"
    "			Er schmeichelte sie doch bei Seit,"
    "			Und von der Linde scholl es weit:"
    "			Juchhe! Juchhe!"
    "			Juchheisa! Heisa! He!"
    "			Geschrei und Fiedelbogen."
    "Alter Bauer:"
    "Herr Doktor, das ist schön von Euch,"
    "Daß Ihr uns heute nicht verschmäht,"
    "Und unter dieses Volksgedräng,"
    "Als ein so Hochgelahrter, geht."
    "So nehmet auch den schönsten Krug,"
    "Den wir mit frischem Trunk gefüllt,"
    "Ich bring ihn zu und wünsche laut,"
    "Daß er nicht nur den Durst Euch stillt:"
    "Die Zahl der Tropfen, die er hegt,"
    "Sei Euren Tagen zugelegt."
    "Faust:"
    "Ich nehme den Erquickungstrank"
    "Erwidr' euch allen Heil und Dank."
    "(Das Volk sammelt sich im Kreis umher.)"
    "Alter Bauer:"
    "Fürwahr, es ist sehr wohl getan,"
    "Daß Ihr am frohen Tag erscheint;"
    "Habt Ihr es vormals doch mit uns"
    "An bösen Tagen gut gemeint!"
    "Gar mancher steht lebendig hier"
    "Den Euer Vater noch zuletzt"
    "Der heißen Fieberwut entriß,"
    "Als er der Seuche Ziel gesetzt."
    "Auch damals Ihr, ein junger Mann,"
    "Ihr gingt in jedes Krankenhaus,"
    "Gar manche Leiche trug man fort,"
    "Ihr aber kamt gesund heraus,"
    "Bestandet manche harte Proben;"
    "Dem Helfer half der Helfer droben."
    "Alle:"
    "Gesundheit dem bewährten Mann,"
    "Daß er noch lange helfen kann!"
    "Faust:"
    "Vor jenem droben steht gebückt,"
    "Der helfen lehrt und Hülfe schickt."
    "Er geht mit Wagnern weiter."
    "Wagner:"
    "Welch ein Gefühl mußt du, o großer Mann,"
    "Bei der Verehrung dieser Menge haben!"
    "O glücklich, wer von seinen Gaben"
    "Solch einen Vorteil ziehen kann!"
    "Der Vater zeigt dich seinem Knaben,"
    "Ein jeder fragt und drängt und eilt,"
    "Die Fiedel stockt, der Tänzer weilt."
    "Du gehst, in Reihen stehen sie,"
    "Die Mützen fliegen in die Höh;"
    "Und wenig fehlt, so beugten sich die Knie,"
    "Als käm das Venerabile."
    "Faust:"
    "Nur wenig Schritte noch hinauf zu jenem Stein,"
    "Hier wollen wir von unsrer Wandrung rasten."
    "Hier saß ich oft gedankenvoll allein"
    "Und quälte mich mit Beten und mit Fasten."
    "An Hoffnung reich, im Glauben fest,"
    "Mit Tränen, Seufzen, Händeringen"
    "Dacht ich das Ende jener Pest"
    "Vom Herrn des Himmels zu erzwingen."
    "Der Menge Beifall tönt mir nun wie Hohn."
    "O könntest du in meinem Innern lesen,"
    "Wie wenig Vater und Sohn"
    "Solch eines Ruhmes wert gewesen!"
    "Mein Vater war ein dunkler Ehrenmann,"
    "Der über die Natur und ihre heil'gen Kreise"
    "In Redlichkeit, jedoch auf seine Weise,"
    "Mit grillenhafter Mühe sann;"
    "Der, in Gesellschaft von Adepten,"
    "Sich in die schwarze Küche schloß,"
    "Und, nach unendlichen Rezepten,"
    "Das Widrige zusammengoß."
    "Da ward ein roter Leu, ein kühner Freier,"
    "Im lauen Bad der Lilie vermählt,"
    "Und beide dann mit offnem Flammenfeuer"
    "Aus einem Brautgemach ins andere gequält."
    "Erschien darauf mit bunten Farben"
    "Die junge Königin im Glas,"
    "Hier war die Arzenei, die Patienten starben,"
    "Und niemand fragte: wer genas?"
    "So haben wir mit höllischen Latwergen"
    "In diesen Tälern, diesen Bergen"
    "Weit schlimmer als die Pest getobt."
    "Ich habe selbst den Gift an Tausende gegeben:"
    "Sie welkten hin, ich muß erleben,"
    "Daß man die frechen Mörder lobt."
    "Wagner:"
    "Wie könnt Ihr Euch darum betrüben!"
    "Tut nicht ein braver Mann genug,"
    "Die Kunst, die man ihm übertrug,"
    "Gewissenhaft und pünktlich auszuüben?"
    "Wenn du als Jüngling deinen Vater ehrst,"
    "So wirst du gern von ihm empfangen;"
    "Wenn du als Mann die Wissenschaft vermehrst,"
    "So kann dein Sohn zu höhrem Ziel gelangen."
    "Faust:"
    "O glücklich, wer noch hoffen kann,"
    "Aus diesem Meer des Irrtums aufzutauchen!"
    "Was man nicht weiß, das eben brauchte man,"
    "Und was man weiß, kann man nicht brauchen."
    "Doch laß uns dieser Stunde schönes Gut"
    "Durch solchen Trübsinn nicht verkümmern!"
    "Betrachte, wie in Abendsonne-Glut"
    "Die grünumgebnen Hütten schimmern."
    "Sie rückt und weicht, der Tag ist überlebt,"
    "Dort eilt sie hin und fördert neues Leben."
    "O daß kein Flügel mich vom Boden hebt"
    "Ihr nach und immer nach zu streben!"
    "Ich säh im ewigen Abendstrahl"
    "Die stille Welt zu meinen Füßen,"
    "Entzündet alle Höhn beruhigt jedes Tal,"
    "Den Silberbach in goldne Ströme fließen."
    "Nicht hemmte dann den göttergleichen Lauf"
    "Der wilde Berg mit allen seinen Schluchten;"
    "Schon tut das Meer sich mit erwärmten Buchten"
    "Vor den erstaunten Augen auf."
    "Doch scheint die Göttin endlich wegzusinken;"
    "Allein der neue Trieb erwacht,"
    "Ich eile fort, ihr ew'ges Licht zu trinken,"
    "Vor mir den Tag und hinter mir die Nacht,"
    "Den Himmel über mir und unter mir die Wellen."
    "Ein schöner Traum, indessen sie entweicht."
    "Ach! zu des Geistes Flügeln wird so leicht"
    "Kein körperlicher Flügel sich gesellen."
    "Doch ist es jedem eingeboren"
    "Daß sein Gefühl hinauf und vorwärts dringt,"
    "Wenn über uns, im blauen Raum verloren,"
    "Ihr schmetternd Lied die Lerche singt;"
    "Wenn über schroffen Fichtenhöhen"
    "Der Adler ausgebreitet schwebt,"
    "Und über Flächen, über Seen"
    "Der Kranich nach der Heimat strebt."
    "Wagner:"
    "Ich hatte selbst oft grillenhafte Stunden,"
    "Doch solchen Trieb hab ich noch nie empfunden."
    "Man sieht sich leicht an Wald und Feldern satt;"
    "Des Vogels Fittich werd ich nie beneiden."
    "Wie anders tragen uns die Geistesfreuden"
    "Von Buch zu Buch, von Blatt zu Blatt!"
    "Da werden Winternächte hold und schön"
    "Ein selig Leben wärmet alle Glieder,"
    "Und ach! entrollst du gar ein würdig Pergamen,"
    "So steigt der ganze Himmel zu dir nieder."
    "Faust:"
    "Du bist dir nur des einen Triebs bewußt,"
    "O lerne nie den andern kennen!"
    "Zwei Seelen wohnen, ach! in meiner Brust,"
    "Die eine will sich von der andern trennen;"
    "Die eine hält, in derber Liebeslust,"
    "Sich an die Welt mit klammernden Organen;"
    "Die andre hebt gewaltsam sich vom Dust"
    "Zu den Gefilden hoher Ahnen."
    "O gibt es Geister in der Luft,"
    "Die zwischen Erd und Himmel herrschend weben"
    "So steiget nieder aus dem goldnen Duft"
    "Und führt mich weg zu neuem, buntem Leben!"
    "Ja, wäre nur ein Zaubermantel mein,"
    "Und trüg er mich in fremde Länder!"
    "Mir sollt er um die köstlichsten Gewänder,"
    "Nicht feil um einen Königsmantel sein."
    "Wagner:"
    "Berufe nicht die wohlbekannte Schar,"
    "Die strömend sich im Dunstkreis überbreitet,"
    "Dem Menschen tausendfältige Gefahr,"
    "Von allen Enden her, bereitet."
    "Von Norden dringt der scharfe Geisterzahn"
    "Auf dich herbei, mit pfeilgespitzten Zungen;"
    "Von Morgen ziehn, vertrocknend, sie heran,"
    "Und nähren sich von deinen Lungen;"
    "Wenn sie der Mittag aus der Wüste schickt,"
    "Die Glut auf Glut um deinen Scheitel häufen"
    "So bringt der West den Schwarm, der erst erquickt,"
    "Um dich und Feld und Aue zu ersäufen."
    "Sie hören gern, zum Schaden froh gewandt,"
    "Gehorchen gern, weil sie uns gern betrügen;"
    "Sie stellen wie vom Himmel sich gesandt,"
    "Und lispeln englisch, wenn sie lügen."
    "Doch gehen wir! Ergraut ist schon die Welt,"
    "Die Luft gekühlt, der Nebel fällt!"
    "Am Abend schätzt man erst das Haus. –"
    "Was stehst du so und blickst erstaunt hinaus?"
    "Was kann dich in der Dämmrung so ergreifen?"
    "Faust:"
    "Siehst du den schwarzen Hund durch Saat und Stoppel streifen?"
    "Wagner:"
    "Ich sah ihn lange schon, nicht wichtig schien er mir."
    "Faust:"
    "Betracht ihn recht! für was hältst du das Tier?"
    "Wagner:"
    "Für einen Pudel, der auf seine Weise"
    "Sich auf der Spur des Herren plagt."
    "Faust:"
    "Bemerkst du, wie in weitem Schneckenkreise"
    "Er um uns her und immer näher jagt?"
    "Und irr ich nicht, so zieht ein Feuerstrudel"
    "Auf seinen Pfaden hinterdrein."
    "Wagner:"
    "Ich sehe nichts als einen schwarzen Pudel;"
    "Es mag bei Euch wohl Augentäuschung sein."
    "Faust:"
    "Mir scheint es, daß er magisch leise Schlingen"
    "Zu künft'gem Band um unsre Füße zieht."
    "Wagner:"
    "Ich seh ihn ungewiß und furchtsam uns umspringen,"
    "Weil er, statt seines Herrn, zwei Unbekannte sieht."
    "Faust:"
    "Der Kreis wird eng, schon ist er nah!"
    "Wagner:"
    "Du siehst! ein Hund, und kein Gespenst ist da."
    "Er knurrt und zweifelt, legt sich auf den Bauch,"
    "Er wedelt. Alles Hundebrauch."
    "Faust:"
    "Geselle dich zu uns! Komm hier!"
    "Wagner:"
    "Es ist ein pudelnärrisch Tier."
    "Du stehest still, er wartet auf;"
    "Du sprichst ihn an, er strebt an dir hinauf;"
    "Verliere was, er wird es bringen,"
    "Nach deinem Stock ins Wasser springen."
    "Faust:"
    "Du hast wohl recht; ich finde nicht die Spur"
    "Von einem Geist, und alles ist Dressur."
    "Wagner:"
    "Dem Hunde, wenn er gut gezogen,"
    "Wird selbst ein weiser Mann gewogen."
    "Ja, deine Gunst verdient er ganz und gar,"
    "Er, der Studenten trefflicher Skolar."
    "(Sie gehen in das Stadttor.)";
    std::transform(message.begin(), message.end(), message.begin(), ::tolower);
    caeserdecrypt(message, 1);
    for (string sentence : walloftext)
    {
        int score = checktext(sentence);
        if (score == bestscore)
        {
            endresult += "\n" + sentence;
        }
        else if  (score > bestscore)
        {
            endresult = sentence;
            bestscore = score;
        }
    }
    //std::cout << "most matches (" << bestscore << ") in word(s):  " << endresult;
}